name: Build with node-gyp

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: cp -f ./build/Release/*.node ./binaries
      - name: Configure Git
        run: |
          git config --global user.email "seesemichaelj@gmail.com"
          git config --global user.name "Mike Seese"
      - run: git add binaries
      - name: Commit
        run: git commit -m "[GitHub Actions] Updated ${{ matrix.os }} NodeJS ${{ matrix.node }} binaries" || true
      - name: Push
        uses: nick-invision/retry@v2
        with:
            timeout_minutes: 1
            max_attempts: 20
            retry_wait_seconds: 5
            command: git pull && git push "https://seesemichaelj:${{ secrets.SECRET }}@github.com/seesemichaelj/uWebSockets.js"
