name: Build with node-gyp

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - name: Update binaries
        run: |
          cp ./build/Release/*.node .
          git status
          git pull origin binaries
          git rev-parse master > source_commit
          git checkout master docs/index.d.ts && mv docs/index.d.ts .
          git config --global user.email "seesemichaelj@gmail.com"
          git config --global user.name "Mike Seese"
          git commit -a -m "[GitHub Actions] Updated ${{ matrix.os }} NodeJS ${{ matrix.node }} binaries" || true
          git push "https://seesemichaelj:${{ secrets.SECRET }}@github.com/seesemichaelj/uWebSockets.js" binaries
