name: Build with node-gyp

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, '[Github Actions]') }} # Prevent recursive builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: cp -f ./build/Release/*.node ./binaries
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
      - run: cp -Force ./build/Release/*.node ./binaries
        if: startsWith(matrix.os, 'windows')
      - name: Configure Git
        run: |
          git config --global user.email "seesemichaelj@gmail.com"
          git config --global user.name "Mike Seese"
          git config pull.rebase true
      - run: git add binaries
      - run: git checkout -b temp_${{ github.sha }} # create it if it doesn't exist
        continue-on-error: true
      - run: git push origin temp_${{ github.sha }}
        continue-on-error: true
      - run: git checkout temp_${{ github.sha }} # checkout if it already existed
      - run: git fetch
      - run: git branch -u origin/temp_${{ github.sha }} temp_${{ github.sha }}
      - name: Commit
        run: git commit -m "[GitHub Actions] Updated ${{ matrix.os }} NodeJS ${{ matrix.node }} binaries" || true
      - name: Push
        uses: nick-invision/retry@v2
        with:
            timeout_minutes: 1
            max_attempts: 20
            retry_wait_seconds: 5
            command: git pull && git push "https://seesemichaelj:${{ secrets.SECRET }}@github.com/seesemichaelj/uWebSockets.js" temp_${{ github.sha }}
